# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4203aecd154961ce1c6107e67467478fae69ea78abef3aa6dcd718e80e0e70ea400f39da72201cf19549ebf8c7fc4f7e3d5ddc5dde869b2f4ceb89cf2d29bd79

test:
  secret_key_base: 119d9c9dc00e0c0a9e2ef216e373f15b6dd3321b90ee91025256d557e24dc5bd5eea759446d2e1e224b5ed789623cab95de2bde76b47c95e9625de03fbc75aea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
